### PR TITLE
Deployment to needed chains

### PR DESCRIPTION
**Pull request by Tritium-VLK**
Factory: 0x6142582f8946bf192a4f80ed643a5856d18a7060
Mock Injector: 0x747c4f7d3fc02b7975779effdf5d1c77105109cb

### CODE REVIEW

**Comment by Tritium-VLK** [comment]
@petrovska-petro Was unable to get verifaction to work anywhere
```
TritsCynterface:ChildGaugeInjectorV2 tritium$ forge script foundry_scripts/InjectorInfraDeployment.s.sol                 --rpc-url gnosis                --slow                 -vvvvv --broadcast --verify --resume
[⠊] Compiling...
No files changed, compilation skipped

Transactions saved to: /Users/tritium/PycharmProjects/ChildGaugeInjectorV2/broadcast/InjectorInfraDeployment.s.sol/100/run-latest.json

Sensitive values saved to: /Users/tritium/PycharmProjects/ChildGaugeInjectorV2/cache/InjectorInfraDeployment.s.sol/100/run-latest.json

Error: 
Missing etherscan key for chain 100
```
onj all chains. Any ideas, or any chance you could just verify?

**Comment by Tritium-VLK** [comment]
Got it

**Comment by Tritium-VLK** [comment]
See https://github.com/BalancerMaxis/bal_addresses/pull/486

**Review by petrovska-petro — APPROVED** [review]
contracts in the shell script are approved across the chains ! 🥳

**Pull request merged**
